### PR TITLE
Deprecate JSON-RPC communications in favor of gRPC

### LINKED ISSUE #3: Deprecate JSON-RPC communication in favor of gRPC

### PR DESCRIPTION
**Pull request by jules**
Fixes #3

### CODE REVIEW

**Comment by jules** [comment]
Client is untested.

**Comment by ggoranov** [comment]
Client tested with TLS, NoTLS, Auth, NoAuth over both tcp and unix socket

**Comment by ggoranov** [comment]
@julesdesmit Can't assign you as a reviewer. Would you review latest commits?

**Comment by jules** [comment]
Done, LGTM.

**Pull request merged**
